local CONSTANTS = {}

CONSTANTS.BASE_WIDTH = 1920
CONSTANTS.BASE_HEIGHT = 1080

CONSTANTS.CARD_WIDTH = 40 * 3.6
CONSTANTS.CARD_HEIGHT = 66 * 3.6

CONSTANTS.HAND_X = 550
CONSTANTS.HAND_Y = 700
CONSTANTS.HAND_WIDTH = 900



return CONSTANTS