local CONSTANTS = {}

CONSTANTS.BASE_WIDTH = 1920
CONSTANTS.BASE_HEIGHT = 1080

CONSTANTS.CARD_WIDTH = 40 * 3.6
CONSTANTS.CARD_HEIGHT = 66 * 3.6

CONSTANTS.SPARKS_X = 730
CONSTANTS.SPARKS_Y = 50
CONSTANTS.SPARKS_WIDTH = 5 * CONSTANTS.CARD_WIDTH + 20
CONSTANTS.SPARKS_HEIGHT = CONSTANTS.CARD_HEIGHT + 20

CONSTANTS.HAND_X = 650
CONSTANTS.HAND_Y = 700
CONSTANTS.HAND_WIDTH = 900

CONSTANTS.DECK_X = 1730
CONSTANTS.DECK_Y = 980
CONSTANTS.DECK_HEIGHT = 300

return CONSTANTS